name: Build & Test

on:
  push:
  pull_request:

jobs:

  test:
    name: 🧪 Test with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Generate Jacoco HTML report
        run: mvn jacoco:report

      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: Test reports
          path: target/site/jacoco

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    needs: [ test ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
