name: Build & Test

on:
  push:
  pull_request:

jobs:

  test:
    name: 🧪 Test with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3.0.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - uses: actions/upload-artifact@v3.0.0
        if: always()
        with:
          name: Test reports
          path: target/surefire-reports
